// <auto-generated />
using System;
using System.Diagnostics.CodeAnalysis;
using Construct.Core.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Construct.Core.Migrations
{
    [DbContext(typeof(SqliteContext))]
    [ExcludeFromCodeCoverage]
    partial class SqliteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("Construct.Core.Database.Model.PrintLog", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BillTo")
                        .HasColumnType("TEXT");

                    b.Property<float>("Cost")
                        .HasColumnType("REAL");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MaterialName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Owed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserHashedId")
                        .HasColumnType("TEXT");

                    b.Property<float>("WeightGrams")
                        .HasColumnType("REAL");

                    b.HasKey("Key");

                    b.HasIndex("MaterialName");

                    b.HasIndex("UserHashedId");

                    b.ToTable("PrintLog");
                });

            modelBuilder.Entity("Construct.Core.Database.Model.PrintMaterial", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<float>("CostPerGram")
                        .HasColumnType("REAL");

                    b.HasKey("Name");

                    b.ToTable("PrintMaterials");
                });

            modelBuilder.Entity("Construct.Core.Database.Model.User", b =>
                {
                    b.Property<string>("HashedId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Permissions")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SignUpTime")
                        .HasColumnType("TEXT");

                    b.HasKey("HashedId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Construct.Core.Database.Model.VisitLog", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserHashedId")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.HasIndex("UserHashedId");

                    b.ToTable("VisitLogs");
                });

            modelBuilder.Entity("Construct.Core.Database.Model.PrintLog", b =>
                {
                    b.HasOne("Construct.Core.Database.Model.PrintMaterial", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialName");

                    b.HasOne("Construct.Core.Database.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserHashedId");

                    b.Navigation("Material");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Construct.Core.Database.Model.VisitLog", b =>
                {
                    b.HasOne("Construct.Core.Database.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserHashedId");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
